### ISSUE TITLE
Fail to clean up report #100

### ISSUE THREAD

**Issue by andgineer** [andgineer/allure-report#9]
https://github.com/andgineer/bitwarden-import-msecure/actions/runs/8858130612/job/24326410693

Report successfully generated to gh-pages-dir/builds/tests/113
Traceback (most recent call last):
  File "/.venv/lib/python3.11/site-packages/github_custom_actions/action_base.py", line 68, in run
    self.main()
  File "/generate-allure-report/app/allure_generate.py", line 98, in main
    self.cleanup_reports()
  File "/generate-allure-report/app/allure_generate.py", line 129, in cleanup_reports
    report.unlink()
  File "/usr/lib/python3.11/pathlib.py", line 1147, in unlink
    os.unlink(self)
IsADirectoryError: [Errno 21] Is a directory: 'gh-pages-dir/builds/tests/100'
Generate Allure Report action v.3
Generating report from allure-results to gh-pages-dir/builds/tests ...
Found 21 report(s) in history, keeping 20
Removing 100 ...

**Comment by pavlo-sv** [comment]
Hello @andgineer, how to fix this error? Getting the same in my config.

**Comment by andgineer** [comment]
Are you using the latest version?
As I see I fixed it so it should not use unlink at all

https://github.com/andgineer/allure-report/commit/41b6e648587e52d3a725e08a460f883d1c8511e2

**Comment by pavlo-sv** [comment]
Updated to 3.4 version and now it works fine. Thanks!
